language: php

php:
  - 5.3
  - 5.4
  - 5.5

services:
  - mysql

script: ant -logger org.apache.tools.ant.NoBannerLogger -Dphpmd.enabled=false -Dpdepend.enabled=false -Dphpcpd.enabled=false -Dphploc.enabled=false -Dcodesniffer.enabled=false
