language: php

php:
  - 5.3
  - 5.4
  - 5.5

services:
  - mysql

before_script: "ant -logger org.apache.tools.ant.NoBannerLogger db:initialize composer:composer"
script: "ant -logger org.apache.tools.ant.NoBannerLogger behat && php vendor/bin/phpunit"
